# Contents

- [Regular Expressions](#reg_ex)
- [NLTK](#nltk)  
    - [Sentence Tokenization](#sent_toke)  
    - [Word Tokenization](#word_toke)  
    - [Stopwords](#stp_wrd)  
    - [N-grams](#ngrm)  
    - [Stemming](#stem)
    - [Lemmatization](#lem)
- [TextBlob](#txt_blb)  
    - [Sentiment Analysis](#sent_anal)
- [Vectorization](#vec)  
    - [CountVectorizer](#cnt_vec)  
    - [TFIDF Vectorizer](#tf_vec)  
- [Topic Modeling](#top_mod)  
    - [LDA](#lda)  
    - [NMF](#nmf)  
- [Word2Vec](#w2v)  

# Regular Expressions <a name="reg_ex"></a>

In [1]:
import re

## match
Searches for match from begginning of the string

In [2]:
# match result
re.match(r'baloney', 'baloney')

<_sre.SRE_Match object; span=(0, 7), match='baloney'>

In [3]:
# no match
re.match(r'baloney', 'caloney')

In [4]:
re.match(r'baloney', 'mebaloneycheese')

In [5]:
re.match(r'baloney', 'baloneycheese')

<_sre.SRE_Match object; span=(0, 7), match='baloney'>

## search
Searches for match anywhere in the string

In [6]:
# match result
re.search(r'spam', 'spam')

<_sre.SRE_Match object; span=(0, 4), match='spam'>

In [7]:
# no match
re.search(r'spam', 'maam')

In [8]:
re.search(r'spam', 'this is some spam over here')

<_sre.SRE_Match object; span=(13, 17), match='spam'>

## findall
Searches for all matches in the string

In [9]:
# match result
re.findall(r'dynasty', 'this is the first dynasty but whose dynasty?')

['dynasty', 'dynasty']

In [10]:
# no match
re.findall(r'dynasty', 'this is the first but whose?')

[]

## General Searching

In [11]:
sample_text = 'purple alice-b@google.com, blah monkey32 bob@abc.com blah dishwasher'

In [12]:
# search for specific character
re.search(r'b', sample_text).group()

'b'

In [13]:
# search for specific character group
re.search(r'bl', sample_text).group()

'bl'

In [14]:
# search for specific charcter group with wildcard
re.search(r'bl.h', sample_text).group()

'blah'

In [15]:
# search for specific character range
re.search(r'[a-c]', sample_text).group()

'a'

In [16]:
# search for general letter
re.search(r'\w', sample_text).group()

'p'

In [17]:
# search for general letter group
re.search(r'\w+', sample_text).group()

'purple'

In [18]:
# search for general number
re.search(r'\d', sample_text).group()

'3'

In [19]:
re.search(r'\d+', sample_text).group()

'32'

In [20]:
# search for general character group followed by general number group
re.search(r'\S+\d+', sample_text).group()

'monkey32'

### Example: email addresses

In [21]:
sample_text

'purple alice-b@google.com, blah monkey32 bob@abc.com blah dishwasher'

In [22]:
# specify groupings in match result
match = re.search(r'(\w+)@(\w+)', sample_text)

In [23]:
# complete match
match.group()

'b@google'

In [24]:
# first group of match result
match.group(1)

'b'

In [25]:
# second group of match result
match.group(2)

'google'

In [26]:
# findall full matches in string
re.findall(r'[\w.-]+@[\w.-]+', sample_text)

['alice-b@google.com', 'bob@abc.com']

In [27]:
# findall with groupings
match = re.findall(r'([\w.-]+)@([\w.-]+)', sample_text)
match

[('alice-b', 'google.com'), ('bob', 'abc.com')]

In [28]:
# first match result
match[0]

('alice-b', 'google.com')

In [29]:
# first group in first match result
match[0][0]

'alice-b'

## Substitution

In [30]:
sample_text

'purple alice-b@google.com, blah monkey32 bob@abc.com blah dishwasher'

In [31]:
# substitute match with specified item
re.sub('com', 'bomb', sample_text)

'purple alice-b@google.bomb, blah monkey32 bob@abc.bomb blah dishwasher'

# NLTK <a name="nltk"></a>

In [32]:
import nltk

In [33]:
text_sample = "The Cat only grinned when it saw Alice. It looked good-natured, she thought: still it had very long claws and a great many teeth, so she felt that it ought to be treated with respect."

In [34]:
# switch to all lowercase for processing
text_sample = text_sample.lower()

## Sentence Tokenization <a name="sent_toke"></a>
Break document into list of sentences

In [35]:
from nltk import tokenize

In [36]:
# break string document into sentences
sentences = tokenize.sent_tokenize(text_sample)
sentences

['the cat only grinned when it saw alice.',
 'it looked good-natured, she thought: still it had very long claws and a great many teeth, so she felt that it ought to be treated with respect.']

## Word Tokenization <a name="word_toke"></a>
Break sentence into list of words

In [37]:
sentences[0]

'the cat only grinned when it saw alice.'

In [38]:
# break sentence into words
words = tokenize.word_tokenize(sentences[0])
words

['the', 'cat', 'only', 'grinned', 'when', 'it', 'saw', 'alice', '.']

## Stopwords <a name="stp_wrd"></a>
Words like "the", "and", "of", etc.

In [39]:
from nltk.corpus import stopwords

In [40]:
# create list of words to remove from corpus
stop = stopwords.words('english')
stop += ['.', ',', '(', ')', "'", '"']
stop = set(stop)

In [41]:
# remove stopwords
cln_words = [w for w in words if w not in stop]
cln_words[:6]

['cat', 'grinned', 'saw', 'alice']

## N-grams <a name="ngrm"></a>
Adjacent words found in text

In [42]:
from nltk.util import ngrams

In [43]:
words

['the', 'cat', 'only', 'grinned', 'when', 'it', 'saw', 'alice', '.']

In [44]:
# create word pairs
bigrams = ngrams(words, 2)
bigrams

<generator object ngrams at 0x7f8aa35544c0>

In [45]:
for gram in bigrams:
    print(gram)

('the', 'cat')
('cat', 'only')
('only', 'grinned')
('grinned', 'when')
('when', 'it')
('it', 'saw')
('saw', 'alice')
('alice', '.')


In [46]:
# create word trios
trigrams = ngrams(words, 3)

In [47]:
for gram in trigrams:
    print(gram)

('the', 'cat', 'only')
('cat', 'only', 'grinned')
('only', 'grinned', 'when')
('grinned', 'when', 'it')
('when', 'it', 'saw')
('it', 'saw', 'alice')
('saw', 'alice', '.')


## Stemming <a name="stem"></a>
Returns root of words

In [48]:
trim_sample = ['grinned', 'saw', 'alice', 'hearts', 'locate']

In [49]:
# initialize stemmer
stemmer = nltk.stem.porter.PorterStemmer()

In [50]:
# stem each word in words list
for word in trim_sample:
    print(word, '->', stemmer.stem(word))

grinned -> grin
saw -> saw
alice -> alic
hearts -> heart
locate -> locat


## Lemmatization <a name="lem"></a>
Similar to stemming but less aggressive

In [51]:
# initialize lemma
lemma=nltk.stem.WordNetLemmatizer()

In [52]:
# lemmatize each word in words list
for word in trim_sample:
    print(word, '->', lemma.lemmatize(word))

grinned -> grinned
saw -> saw
alice -> alice
hearts -> heart
locate -> locate


# Spacy

In [53]:
import spacy

In [54]:
# load english parser
nlp = spacy.load('en')

In [55]:
phrase = sentences[0]

In [56]:
# parse words
for word in nlp(phrase):
    print(word)

the
cat
only
grinned
when
it
saw
alice
.


In [57]:
# return simplified parts of speech
for word in nlp(phrase):
    print(word.pos_)

DET
NOUN
ADV
VERB
ADV
PRON
VERB
NOUN
PUNCT


In [58]:
# return complex parts of speech
for word in nlp(phrase):
    print(word.tag_)

DT
NN
RB
VBD
WRB
PRP
VBD
NN
.


In [59]:
# visualize sentence structure
spacy.displacy.render(nlp(phrase), style='dep')

In [60]:
# verbose sentence structure
for word in nlp(phrase):
    print (word.text, word.tag_, word.head.text, word.dep_)

the DT cat det
cat NN grinned nsubj
only RB grinned advmod
grinned VBD grinned ROOT
when WRB saw advmod
it PRP saw nsubj
saw VBD grinned advcl
alice NN saw dobj
. . grinned punct


# TextBlob <a name="txt_blb"></a>

In [61]:
from textblob import TextBlob

In [62]:
# break input into sentences
TextBlob(text_sample).sentences

[Sentence("the cat only grinned when it saw alice."),
 Sentence("it looked good-natured, she thought: still it had very long claws and a great many teeth, so she felt that it ought to be treated with respect.")]

In [63]:
# break input into words
TextBlob(sentences[0]).words

WordList(['the', 'cat', 'only', 'grinned', 'when', 'it', 'saw', 'alice'])

In [64]:
# retrieve word counts
TextBlob(sentences[0]).word_counts

defaultdict(int,
            {'the': 1,
             'cat': 1,
             'only': 1,
             'grinned': 1,
             'when': 1,
             'it': 1,
             'saw': 1,
             'alice': 1})

## Sentiment Analysis <a name="sent_anal"></a> 
- Polarity scale: -1 (negative) to 1 (positive)  
- Subjectivity scale: 0 (very objective) to 1 (very subjective)

In [65]:
# positive or negative polarity for document
TextBlob(text_sample).sentiment

Sentiment(polarity=0.30875, subjectivity=0.6925)

In [66]:
# positive or negative polarity for sentence
TextBlob(sentences[0]).sentiment

Sentiment(polarity=0.0, subjectivity=1.0)

# Document Data

In [67]:
from nltk.corpus import movie_reviews

In [68]:
# grab range of filenames from corpus
fileids = movie_reviews.fileids('pos')[:100]
# create list of words for each file
doc_words = [movie_reviews.words(fileid) for fileid in fileids]
# create list of sentences by combining words back into sentences for each file
pos_docs = [' '.join(words) for words in doc_words]

In [69]:
fileids = movie_reviews.fileids('neg')[:100]
doc_words = [movie_reviews.words(fileid) for fileid in fileids]
neg_docs = [' '.join(words) for words in doc_words]

In [70]:
# combine into one variable
documents = pos_docs + neg_docs

# Vectorization <a name="vec"></a>
Bag of Words (BOW)

In [71]:
import pandas as pd

## CountVectorizer <a name="cnt_vec"></a>
Returns word counts per document

In [72]:
from sklearn.feature_extraction.text import CountVectorizer

In [73]:
# create instance of CountVectorizer
cv_vectorizer = CountVectorizer(stop_words='english', # remove inconsequential words
                             max_df=0.95, # ignore most frequent words (corpus-specific stopwords)
                             min_df=0.05 # ignore least frequent words (irrelevant words)
                            )

In [74]:
# learn vocabulary from input documents
cv_vectorizer.fit(documents)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.95, max_features=None, min_df=0.05,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [75]:
# transform documents into document-term matrix
X = cv_vectorizer.transform(documents)
X

<200x949 sparse matrix of type '<class 'numpy.int64'>'
	with 21677 stored elements in Compressed Sparse Row format>

In [76]:
# return matrix of term counts per document
X.toarray()

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [77]:
# return tokens from documents
cv_vectorizer.get_feature_names()[:20]

['10',
 '20',
 '30',
 'ability',
 'able',
 'absolutely',
 'academy',
 'act',
 'acting',
 'action',
 'actions',
 'actor',
 'actors',
 'acts',
 'actual',
 'actually',
 'adaptation',
 'add',
 'addition',
 'adds']

In [78]:
# create dataframe of document-term matrix
cv_df = pd.DataFrame(X.toarray(), columns=[cv_vectorizer.get_feature_names()])
cv_df.head()

10 20 30 ability able absolutely academy act acting action  ...  write  \
0  0  0  1       0    0          0       0   0      1      0  ...      0   
1  0  0  0       0    0          0       0   0      0      0  ...      0   
2  0  0  0       0    0          1       0   0      1      0  ...      0   
3  0  0  0       0    0          0       1   5      1      0  ...      0   
4  0  0  0       0    0          0       0   0      0      0  ...      0   

  writer writing written wrong year years yes york young  
0      0       0       0     0    0     0   0    0     0  
1      0       0       0     0    1     0   0    0     0  
2      0       0       0     0    2     0   0    0     0  
3      0       0       0     0    0     1   0    1     1  
4      0       0       0     0    0     0   0    1     0  

[5 rows x 949 columns]

### Add lemmatizer

In [79]:
import nltk
from nltk import tokenize

In [80]:
lemma=nltk.stem.WordNetLemmatizer()
# lemmatize function
def lemma_func(document):
    return [lemma.lemmatize(word) for word in tokenize.word_tokenize(document)]

In [81]:
# add lemmatizer to vectorizer
cv_vectorizer = CountVectorizer(stop_words='english',
                             max_df=0.95,
                             min_df=0.05,
                             tokenizer=lemma_func
                            )

In [82]:
X_lem = cv_vectorizer.fit_transform(documents)

In [83]:
cv_df_lem = pd.DataFrame(X_lem.toarray(), columns=[cv_vectorizer.get_feature_names()])
cv_df_lem.head()

!  $  &   (   )  * --  /  1 10  ...  wouldn write writer writing written  \
0  0  0  0  18  18  0  0  2  0  0  ...       0     0      0       0       0   
1  0  0  0  10  10  0  0  1  0  0  ...       0     0      0       0       0   
2  0  0  0   1   1  0  0  1  0  0  ...       0     0      0       0       0   
3  0  0  0  10  10  0  2  0  1  0  ...       0     0      0       0       0   
4  1  0  0   4   4  0  3  1  0  0  ...       0     0      0       0       0   

  wrong year yes york young  
0     0    0   0    0     0  
1     0    1   0    0     0  
2     0    2   0    0     0  
3     0    1   0    1     1  
4     0    0   0    1     0  

[5 rows x 974 columns]

## TFIDF Vectorizer <a name="tf_vec"></a>
Returns weights of words per document normalized against occurence in entire corpus

In [84]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [85]:
# create instance of TFIDF vectorizer
tf_vectorizer = TfidfVectorizer(stop_words='english', # remove inconsequential words
                             max_df=0.95, # ignore most frequent words (corpus-specific stopwords)
                             min_df=0.05 # ignore least frequent words (irrelevant words)
                            )

In [86]:
# learn vocabulary from input documents
tf_vectorizer.fit(documents)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.95, max_features=None, min_df=0.05,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [87]:
# transform documents into document-term matrix
X = tf_vectorizer.transform(documents)
X

<200x949 sparse matrix of type '<class 'numpy.float64'>'
	with 21677 stored elements in Compressed Sparse Row format>

In [88]:
# return matrix of normalized term counts
X.toarray()

array([[0.        , 0.        , 0.08169609, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [89]:
# return tokens from documents
tf_vectorizer.get_feature_names()[:20]

['10',
 '20',
 '30',
 'ability',
 'able',
 'absolutely',
 'academy',
 'act',
 'acting',
 'action',
 'actions',
 'actor',
 'actors',
 'acts',
 'actual',
 'actually',
 'adaptation',
 'add',
 'addition',
 'adds']

In [90]:
# create dataframe of document-term matrix
tf_df = pd.DataFrame(X.toarray(), columns=[tf_vectorizer.get_feature_names()])
tf_df.head()

10   20        30 ability able absolutely   academy       act    acting  \
0  0.0  0.0  0.081696     0.0  0.0   0.000000  0.000000  0.000000  0.050323   
1  0.0  0.0  0.000000     0.0  0.0   0.000000  0.000000  0.000000  0.000000   
2  0.0  0.0  0.000000     0.0  0.0   0.106398  0.000000  0.000000  0.069607   
3  0.0  0.0  0.000000     0.0  0.0   0.000000  0.067824  0.309602  0.042673   
4  0.0  0.0  0.000000     0.0  0.0   0.000000  0.000000  0.000000  0.000000   

  action    ...    write writer writing written wrong      year     years  \
0    0.0    ...      0.0    0.0     0.0     0.0   0.0  0.000000  0.000000   
1    0.0    ...      0.0    0.0     0.0     0.0   0.0  0.042467  0.000000   
2    0.0    ...      0.0    0.0     0.0     0.0   0.0  0.142731  0.000000   
3    0.0    ...      0.0    0.0     0.0     0.0   0.0  0.000000  0.038906   
4    0.0    ...      0.0    0.0     0.0     0.0   0.0  0.000000  0.000000   

   yes      york     young  
0  0.0  0.000000  0.000000  
1  0.0  0.000000  0.000000  
2  0.0  0.000000  0.000000  
3  0.0  0.065228  0.040692  
4  0.0  0.085248  0.000000  

[5 rows x 949 columns]

### Add lemmatizer

In [91]:
import nltk
from nltk import tokenize

In [92]:
lemma=nltk.stem.WordNetLemmatizer()
# lemmatize function
def lemma_func(document):
    return [lemma.lemmatize(word) for word in tokenize.word_tokenize(document)]

In [93]:
# add lemmatizer to vectorizer
tf_vectorizer = TfidfVectorizer(stop_words='english',
                             max_df=0.95,
                             min_df=0.05,
                             tokenizer=lemma_func
                            )

In [94]:
X_lem = tf_vectorizer.fit_transform(documents)

In [95]:
tf_df_lem = pd.DataFrame(X_lem.toarray(), columns=[tf_vectorizer.get_feature_names()])
tf_df_lem.head()

!    $    &         (         )    *        --         /         1  \
0  0.000000  0.0  0.0  0.324615  0.324615  0.0  0.000000  0.080978  0.000000   
1  0.000000  0.0  0.0  0.178666  0.178666  0.0  0.000000  0.040113  0.000000   
2  0.000000  0.0  0.0  0.030684  0.030684  0.0  0.000000  0.068889  0.000000   
3  0.000000  0.0  0.0  0.144143  0.144143  0.0  0.057687  0.000000  0.045836   
4  0.043287  0.0  0.0  0.090245  0.090245  0.0  0.135437  0.050653  0.000000   

    10    ...    wouldn write writer writing written wrong      year  yes  \
0  0.0    ...       0.0   0.0    0.0     0.0     0.0   0.0  0.000000  0.0   
1  0.0    ...       0.0   0.0    0.0     0.0     0.0   0.0  0.029770  0.0   
2  0.0    ...       0.0   0.0    0.0     0.0     0.0   0.0  0.102252  0.0   
3  0.0    ...       0.0   0.0    0.0     0.0     0.0   0.0  0.024018  0.0   
4  0.0    ...       0.0   0.0    0.0     0.0     0.0   0.0  0.000000  0.0   

       york     young  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.049062  0.030607  
4  0.076792  0.000000  

[5 rows x 974 columns]

# Topic Modeling <a name="top_mod"></a>

## LDA <a name="lda"></a>

In [96]:
from sklearn.decomposition import LatentDirichletAllocation

In [97]:
# create instance of model, input number of topics to output
lda = LatentDirichletAllocation(n_components=5)

In [98]:
# fit model to vectorized data
lda.fit(cv_df)

/home/kevcon/anaconda3/lib/python3.6/site-packages/sklearn/decomposition/online_lda.py:536: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7, learning_method=None,
             learning_offset=10.0, max_doc_update_iter=100, max_iter=10,
             mean_change_tol=0.001, n_components=5, n_jobs=1,
             n_topics=None, perp_tol=0.1, random_state=None,
             topic_word_prior=None, total_samples=1000000.0, verbose=0)

In [99]:
# documents x token weights
lda.transform(cv_df)[:10]

array([[1.24604687e-03, 1.25159859e-03, 9.95031536e-01, 1.23552344e-03,
        1.23529533e-03],
       [1.21405420e-03, 9.95139293e-01, 1.23283544e-03, 1.20579226e-03,
        1.20802524e-03],
       [1.76734809e-03, 1.94730407e-01, 7.99978887e-01, 1.76449959e-03,
        1.75885804e-03],
       [8.89325347e-04, 2.29046055e-01, 7.68304897e-01, 8.79398968e-04,
        8.80323683e-04],
       [1.45952355e-03, 1.46205827e-03, 9.94201780e-01, 1.44272554e-03,
        1.43391241e-03],
       [8.99954227e-01, 1.13620738e-03, 9.66703656e-02, 1.11638006e-03,
        1.12281949e-03],
       [9.00112835e-04, 9.06323575e-04, 9.96417939e-01, 8.87666769e-04,
        8.87957463e-04],
       [1.54117858e-03, 3.74655377e-02, 9.57924644e-01, 1.52574150e-03,
        1.54289806e-03],
       [3.87778001e-03, 3.83077022e-03, 9.84812133e-01, 3.73971778e-03,
        3.73959896e-03],
       [2.14372108e-03, 2.16086180e-03, 9.91444933e-01, 2.13406311e-03,
        2.11642130e-03]])

In [100]:
# topics x token weights
lda.components_

array([[ 0.28083274,  0.25329061,  2.27522101, ...,  0.29502914,
         0.39713227,  4.12607306],
       [ 2.02606933,  1.48593537,  0.99162553, ...,  0.64101285,
         3.17636903, 16.05410892],
       [34.36120637, 10.43244872,  7.10980683, ..., 21.00318235,
        12.98471719, 55.73678787],
       [ 0.37940623,  0.29994062,  0.29585704, ...,  0.93878458,
         0.27527451,  0.38054519],
       [ 0.25264617,  0.43341995,  0.27032731, ...,  0.25881906,
         0.25423221,  1.74451415]])

In [101]:
# tokens from vectorizer
cv_vectorizer.get_feature_names()[:20]

['!',
 '$',
 '&',
 '(',
 ')',
 '*',
 '--',
 '/',
 '1',
 '10',
 '2',
 '20',
 '3',
 '30',
 '4',
 '5',
 '90',
 ':',
 ';',
 '?']

In [102]:
# return index of top five tokens in first topic
lda.components_[0].argsort()[::-1][:5]

array([226, 593, 159, 783, 186])

In [103]:
# return top five tokens in first topic
[cv_vectorizer.get_feature_names()[i] for i in lda.components_[0].argsort()[::-1][:5]]

['depth', 'number', 'climax', 'son', 'control']

In [104]:
# function to print top words of topic model
def print_top_words(model, feature_names, n_top_words):
    for index, topic in enumerate(model.components_):
        message = "\nTopic #{}:".format(index)
        message += " ".join([feature_names[i] for i in topic.argsort()[:-n_top_words - 1 :-1]])
        print(message)
        print("="*70)

In [105]:
print_top_words(lda, cv_vectorizer.get_feature_names(), 5)


Topic #0:depth number climax son control

Topic #1:excellent kid material bringing brings

Topic #2:excellent material kid human flat

Topic #3:public excellent mother good le

Topic #4:husband effort kevin got obvious


## NMF <a name="nmf"></a>

In [106]:
from sklearn.decomposition import NMF

In [107]:
# create instance of model, input number of topics to output
nmf = NMF(n_components=5)

In [108]:
# fit model to vectorized data
nmf.fit(tf_df)

NMF(alpha=0.0, beta_loss='frobenius', init=None, l1_ratio=0.0, max_iter=200,
  n_components=5, random_state=None, shuffle=False, solver='cd',
  tol=0.0001, verbose=0)

In [109]:
# documents x topic weights
nmf.transform(tf_df)[:10]

array([[0.08486403, 0.1097091 , 0.02818792, 0.04272616, 0.08887138],
       [0.03820497, 0.04980193, 0.14316692, 0.02815628, 0.04289352],
       [0.        , 0.15244572, 0.17079746, 0.0333816 , 0.        ],
       [0.09941769, 0.06814112, 0.17951058, 0.        , 0.07193351],
       [0.00729926, 0.22312447, 0.        , 0.        , 0.15105189],
       [0.03916537, 0.00178897, 0.29181475, 0.        , 0.0230662 ],
       [0.16978842, 0.0190899 , 0.08371953, 0.        , 0.10275037],
       [0.10979501, 0.08164295, 0.18286567, 0.        , 0.        ],
       [0.09403262, 0.        , 0.12447781, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.42461379]])

In [110]:
# topics x token weights
nmf.components_

array([[0.00000000e+00, 1.99040667e-04, 9.42186835e-03, ...,
        3.65714356e-02, 1.14213976e-02, 2.37983536e-02],
       [0.00000000e+00, 1.59402510e-02, 5.42605632e-03, ...,
        3.63157435e-02, 1.15812863e-02, 8.29129336e-03],
       [0.00000000e+00, 9.24277998e-03, 2.05835027e-02, ...,
        6.14186373e-03, 1.79089373e-02, 1.76850646e-01],
       [6.37720030e-01, 2.10014461e-02, 0.00000000e+00, ...,
        2.36474718e-02, 0.00000000e+00, 7.88276000e-02],
       [0.00000000e+00, 3.05980882e-02, 3.73418679e-02, ...,
        1.31318047e-03, 5.80156296e-02, 1.41947575e-02]])

In [111]:
# tokens from vectorizer
tf_vectorizer.get_feature_names()[:20]

['!',
 '$',
 '&',
 '(',
 ')',
 '*',
 '--',
 '/',
 '1',
 '10',
 '2',
 '20',
 '3',
 '30',
 '4',
 '5',
 '90',
 ':',
 ';',
 '?']

In [112]:
# function to print top words of topic model
def print_top_words(model, feature_names, n_top_words):
    for index, topic in enumerate(model.components_):
        message = "\nTopic #{}:".format(index)
        message += " ".join([feature_names[i] for i in topic.argsort()[:-n_top_words - 1 :-1]])
        print(message)
        print("="*70)

In [113]:
print_top_words(nmf, tf_vectorizer.get_feature_names(), 5)


Topic #0:excellent bringing son brings kid

Topic #1:material kid previous incredible human

Topic #2:kevin effort life english williams

Topic #3:! meet appears excellent human

Topic #4:10 liked experience alien release


# Word2Vec <a name="w2v"></a>
Find similarity between words based on given corpus

In [114]:
import gensim

## Preprocess

In [115]:
from nltk.corpus import stopwords
from nltk import tokenize

In [116]:
stoplist = stopwords.words('english')
stoplist += ['.', ',', '(', ')', "'", '"']
stoplist = set(stop)

In [127]:
# create word list per document while removing stopwords
doc_words = [[word for word in tokenize.word_tokenize(document.lower()) if word not in stoplist]
         for document in documents]

## Model

### Continuous Bag of Words (CBOW)
Predicts word from context

In [118]:
# initialize model
model = gensim.models.Word2Vec(doc_words, size=100, window=5, min_count=1, workers=2)

In [119]:
# find similar words in corpus
model.wv.most_similar(positive='director')

/home/kevcon/anaconda3/lib/python3.6/site-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('film', 0.9999442100524902),
 ('-', 0.9999411702156067),
 (';', 0.9999388456344604),
 ('like', 0.9999374151229858),
 ('movie', 0.9999364018440247),
 ('also', 0.9999359846115112),
 ('around', 0.9999359846115112),
 ('even', 0.9999354481697083),
 ('characters', 0.9999321699142456),
 (':', 0.9999303221702576)]

In [120]:
# rate similarity between two words in corpus
model.wv.similarity(w1='director', w2='actor')

/home/kevcon/anaconda3/lib/python3.6/site-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


0.999842

### skip-gram
Predicts context from word

In [121]:
# initialize model
model = gensim.models.Word2Vec(doc_words, size=100, window=10, min_count=1, workers=2, sg=1)

In [122]:
# find similar words in corpus
model.wv.most_similar(positive='director')

/home/kevcon/anaconda3/lib/python3.6/site-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('writer', 0.995871901512146),
 ('9', 0.9939578771591187),
 ('6', 0.9934859275817871),
 ('5', 0.9923529624938965),
 ('crow', 0.9886167049407959),
 ('girlfight', 0.9878637194633484),
 ('salvation', 0.9868960380554199),
 ('4', 0.9865810871124268),
 ('highway', 0.985334038734436),
 ('1', 0.984813392162323)]

In [123]:
# rate similarity between two words in corpus
model.wv.similarity(w1='director', w2='actor')

/home/kevcon/anaconda3/lib/python3.6/site-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


0.95061773