# Contents
- [Array Manipulation](#arr_man)
    - General
    - Ranges
    - Generate Random
    - Sorting
- [Vectorize Function](#vec_fun)
- [Linear Algebra](#lin_al)

In [1]:
import numpy as np

# Array Manipulation <a name="arr_man"></a>

## General

In [2]:
# create array
np.array(range(5))

array([0, 1, 2, 3, 4])

In [3]:
# create multi-dimensional array (input by row)
np.array([[5, 4, 3, 2, 1], [1, 2, 3, 4, 5]])

array([[5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])

In [4]:
# create array of zeros
np.zeros([5, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# create array of ones
np.ones([5, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Ranges

In [6]:
# step input to create evenly spaced array between values
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
# number of steps input to create evenly spaced array between values
np.linspace(1, 3, 5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [8]:
# number of steps input to create log scale of point between log(start) and log(end)
np.logspace(1, 3, 5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [9]:
# space points between start and stop in log scale
np.exp(np.linspace(np.log(1), np.log(3), 5))

array([1.        , 1.31607401, 1.73205081, 2.27950706, 3.        ])

## Generate Random

In [10]:
# create array of random values between 0 and 1
np.random.random((3, 3))

array([[0.34580263, 0.44492082, 0.37131942],
       [0.87406935, 0.71552658, 0.24250499],
       [0.82956247, 0.33620418, 0.52617648]])

In [11]:
# define seed for consistency
np.random.seed(0)
print(np.random.random())
np.random.seed(0)
print(np.random.random())
print(np.random.random())

0.5488135039273248
0.5488135039273248
0.7151893663724195


In [12]:
# create array of random ints between specified range
np.random.randint(0, 100, [3, 5])

array([[67, 67,  9, 83, 21],
       [36, 87, 70, 88, 88],
       [12, 58, 65, 39, 87]])

In [13]:
items = [1, 5, 99, 'tulsa']

In [14]:
# select random value from list
np.random.choice(items)

'99'

In [15]:
# select random sample from list with probability distribution
np.random.choice(items, size=5, replace=True, p=[0, 0.25, 0.25, 0.5])

array(['tulsa', 'tulsa', '5', '5', '5'], dtype='<U21')

In [16]:
# shuffle values in list (in place)
np.random.shuffle(items)

In [17]:
items

[99, 1, 5, 'tulsa']

In [18]:
# random value from normal distribution - input is mean, std dev and size
np.random.normal(0, 1, 3)

array([ 1.41437719, -0.12405066,  2.00815709])

## Sorting

In [19]:
# return array of indicies to order input array (ascending)
np.argsort(np.array([5, 18, 3, 6, 14]))

array([2, 0, 3, 4, 1])

In [20]:
# return ordered list
x = np.array([5, 18, 3, 6, 14])
x[np.argsort(x)]

array([ 3,  5,  6, 14, 18])

In [21]:
# return array of indicies to order input array (descending)
x.argsort()[::-1]

array([1, 4, 3, 0, 2])

## Shape

In [22]:
X = np.array(np.random.randint(0, 100, (3, 5)))
X

array([[39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35],
       [75, 55, 28, 34,  0]])

In [23]:
np.transpose(X)

array([[39, 32, 75],
       [32, 31, 55],
       [65, 74, 28],
       [ 9, 23, 34],
       [57, 35,  0]])

In [24]:
# create 1D array
X.flatten()

array([39, 32, 65,  9, 57, 32, 31, 74, 23, 35, 75, 55, 28, 34,  0])

In [25]:
# reshape array
np.reshape(X, (5, 3))

array([[39, 32, 65],
       [ 9, 57, 32],
       [31, 74, 23],
       [35, 75, 55],
       [28, 34,  0]])

In [26]:
Y = np.random.randint(0, 10, [3, 1])
Y

array([[0],
       [4],
       [5]])

In [27]:
# combine arrays horizontally (by column)
np.hstack((X, Y))

array([[39, 32, 65,  9, 57,  0],
       [32, 31, 74, 23, 35,  4],
       [75, 55, 28, 34,  0,  5]])

In [28]:
Z = np.random.randint(0, 10, [1, 5])
Z

array([[5, 6, 8, 4, 1]])

In [29]:
# combine arrays vertically (by row)
np.vstack((X, Z))

array([[39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35],
       [75, 55, 28, 34,  0],
       [ 5,  6,  8,  4,  1]])

## Interweave Arrays

In [2]:
A = np.array(np.random.randint(0, 100, (3, 5)))
A

array([[89, 98, 45, 81, 60],
       [92,  1,  9, 46, 20],
       [ 0, 65, 25, 22, 77]])

In [3]:
B = np.array(np.random.randint(0, 100, (3, 5)))
B

array([[37,  2, 28,  7, 12],
       [45, 44, 24, 16, 42],
       [88, 76,  6, 90, 45]])

In [8]:
# create empty array of final interweaved dimensions
C = np.empty((A.shape[0]*2, A.shape[1]))

In [9]:
# populate all even rows
C[0::2, :] = A
# populate all odd rows
C[1::2, :] = B

In [10]:
# final array
C

array([[89., 98., 45., 81., 60.],
       [37.,  2., 28.,  7., 12.],
       [92.,  1.,  9., 46., 20.],
       [45., 44., 24., 16., 42.],
       [ 0., 65., 25., 22., 77.],
       [88., 76.,  6., 90., 45.]])

# Vectorize Function <a name="vec_fun"></a>

In [30]:
def vec_fun(x):
    return(x * 10)

In [31]:
nums = np.array([3, 7, 1])

In [32]:
# apply function to array
np.vectorize(vec_fun)(nums)

array([30, 70, 10])

In [33]:
def vec_fun_2(x, y):
    return(x + y)

In [34]:
nums2 = np.array([5, 8, 1])

In [35]:
# apply function to multiple arrays
np.vectorize(vec_fun_2)(nums, nums2)

array([ 8, 15,  2])

In [36]:
# apply function to array and single value
np.vectorize(vec_fun_2)(nums, 2)

array([5, 9, 3])

# Linear Algebra <a name="lin_al"></a>

## Matrix definitions

In [37]:
np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
# create matrix of zeros
np.mat(np.zeros((5, 5)))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [39]:
# create matrix of ones
np.mat(np.ones((5, 5)))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [40]:
# create identity matrix
np.mat(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Matrix manipulation

In [41]:
A = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [42]:
# matrix spacial dimension
A.ndim

2

In [43]:
# length of matrix
len(A)

3

In [44]:
# matrix shape dimensions
A.shape

(3, 3)

In [45]:
# matrix number of digits
A.size

9

In [46]:
# select selement in third row, second column
A[2, 1]

8

In [47]:
B = np.mat([[6], [2], [-1]])
B

matrix([[ 6],
        [ 2],
        [-1]])

In [48]:
B.shape

(3, 1)

In [49]:
C = A * B
C

matrix([[ 7],
        [28],
        [49]])

In [50]:
C.shape

(3, 1)

## Matrix mulitplication with arrays

In [51]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
# create row vector
B = np.array([[6, 2, -1]])
B

array([[ 6,  2, -1]])

In [53]:
# transpose array into column vector
B.T

array([[ 6],
       [ 2],
       [-1]])

In [54]:
# matrix multiplication
A @ B.T

array([[ 7],
       [28],
       [49]])

In [55]:
np.dot(A, B.T)

array([[ 7],
       [28],
       [49]])