# Linear Algebra with numpy

In [2]:
import numpy as np

## Array definitions

In [11]:
# create array
np.array(range(5))

array([0, 1, 2, 3, 4])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [20]:
np.random.random((3, 3))

array([[0.39479254, 0.24673334, 0.30149902],
       [0.63532201, 0.96280983, 0.26225304],
       [0.51141799, 0.631582  , 0.43793439]])

In [4]:
np.argsort(np.array([5, 18, 3, 6, 14]))

array([2, 0, 3, 4, 1])

## Matrix definitions

In [24]:
np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
# create matrix of zeros
np.mat(np.zeros((5, 5)))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [10]:
# create matrix of ones
np.mat(np.ones((5, 5)))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [22]:
# create identity matrix
np.mat(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Matrix manipulation

In [35]:
A = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
# matrix spacial dimension
A.ndim

2

In [31]:
# length of matrix
len(A)

3

In [26]:
# matrix shape dimensions
A.shape

(3, 3)

In [30]:
# matrix number of digits
A.size

9

In [40]:
# select selement in third row, second column
A[2, 1]

8

In [36]:
B = np.mat([[6], [2], [-1]])
B

matrix([[ 6],
        [ 2],
        [-1]])

In [28]:
B.shape

(3, 1)

In [33]:
C = A * B
C

matrix([[ 7],
        [28],
        [49]])

In [34]:
C.shape

(3, 1)

## Matrix mulitplication with arrays

In [41]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# create row vector
B = np.array([[6, 2, -1]])
B

array([[ 6,  2, -1]])

In [43]:
# transpose array into column vector
B.T

array([[ 6],
       [ 2],
       [-1]])

In [44]:
# matrix multiplication
A @ B.T

array([[ 7],
       [28],
       [49]])

In [45]:
np.dot(A, B.T)

array([[ 7],
       [28],
       [49]])