# Contents
- Array Manipulation
- Linear Algebra

In [1]:
import numpy as np

# Array Manipulation

In [2]:
# create array
np.array(range(5))

array([0, 1, 2, 3, 4])

In [3]:
# create multi-dimensional array (input by row)
np.array([[5, 4, 3, 2, 1], [1, 2, 3, 4, 5]])

array([[5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])

In [4]:
# create array of zeros
np.zeros([5, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# create array of ones
np.ones([5, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# step input to create evenly spaced array between values
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
# number of steps input to create evenly spaced array between values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# create array of values in logspace
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [9]:
# create array of random values
np.random.random((3, 3))

array([[0.12933985, 0.57605563, 0.76382711],
       [0.03643686, 0.42126292, 0.5985391 ],
       [0.5655574 , 0.17606316, 0.38563476]])

In [10]:
# create array of random ints
np.random.randint(0, 100, [3, 5])

array([[25, 23, 70, 58, 43],
       [ 3, 86, 14, 29, 68],
       [ 5, 48,  3, 57,  5]])

In [11]:
# return array of indicies to order input array (ascending)
np.argsort(np.array([5, 18, 3, 6, 14]))

array([2, 0, 3, 4, 1])

In [12]:
x = np.array([5, 18, 3, 6, 14])
x[np.argsort(x)]

array([ 3,  5,  6, 14, 18])

## Shape

In [13]:
X = np.array(np.random.randint(0, 100, (3, 5)))
X

array([[79, 48, 51,  3,  3],
       [32, 96, 94, 24,  2],
       [59, 34, 11, 90, 95]])

In [14]:
np.transpose(X)

array([[79, 32, 59],
       [48, 96, 34],
       [51, 94, 11],
       [ 3, 24, 90],
       [ 3,  2, 95]])

In [15]:
# create 1D array
X.flatten()

array([79, 48, 51,  3,  3, 32, 96, 94, 24,  2, 59, 34, 11, 90, 95])

In [16]:
# reshape array
np.reshape(X, (5, 3))

array([[79, 48, 51],
       [ 3,  3, 32],
       [96, 94, 24],
       [ 2, 59, 34],
       [11, 90, 95]])

In [17]:
Y = np.random.randint(0, 10, [3, 1])
Y

array([[9],
       [1],
       [4]])

In [18]:
# combine arrays horizontally (by column)
np.hstack((X, Y))

array([[79, 48, 51,  3,  3,  9],
       [32, 96, 94, 24,  2,  1],
       [59, 34, 11, 90, 95,  4]])

In [19]:
Z = np.random.randint(0, 10, [1, 5])
Z

array([[4, 7, 2, 5, 5]])

In [20]:
# combine arrays vertically (by row)
np.vstack((X, Z))

array([[79, 48, 51,  3,  3],
       [32, 96, 94, 24,  2],
       [59, 34, 11, 90, 95],
       [ 4,  7,  2,  5,  5]])

# Linear Algebra

## Matrix definitions

In [21]:
np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
# create matrix of zeros
np.mat(np.zeros((5, 5)))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
# create matrix of ones
np.mat(np.ones((5, 5)))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [24]:
# create identity matrix
np.mat(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Matrix manipulation

In [25]:
A = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
# matrix spacial dimension
A.ndim

2

In [27]:
# length of matrix
len(A)

3

In [28]:
# matrix shape dimensions
A.shape

(3, 3)

In [29]:
# matrix number of digits
A.size

9

In [30]:
# select selement in third row, second column
A[2, 1]

8

In [31]:
B = np.mat([[6], [2], [-1]])
B

matrix([[ 6],
        [ 2],
        [-1]])

In [32]:
B.shape

(3, 1)

In [33]:
C = A * B
C

matrix([[ 7],
        [28],
        [49]])

In [34]:
C.shape

(3, 1)

## Matrix mulitplication with arrays

In [35]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
# create row vector
B = np.array([[6, 2, -1]])
B

array([[ 6,  2, -1]])

In [37]:
# transpose array into column vector
B.T

array([[ 6],
       [ 2],
       [-1]])

In [38]:
# matrix multiplication
A @ B.T

array([[ 7],
       [28],
       [49]])

In [39]:
np.dot(A, B.T)

array([[ 7],
       [28],
       [49]])