# Contents
- [Array Manipulation](#arr_man)
- [Vectorization](#vect)
- [Linear Algebra](#lin_al)

In [1]:
import numpy as np

# Array Manipulation <a name="arr_man"></a>

In [2]:
# create array
np.array(range(5))

array([0, 1, 2, 3, 4])

In [3]:
# create multi-dimensional array (input by row)
np.array([[5, 4, 3, 2, 1], [1, 2, 3, 4, 5]])

array([[5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])

In [4]:
# create array of zeros
np.zeros([5, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# create array of ones
np.ones([5, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# step input to create evenly spaced array between values
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
# number of steps input to create evenly spaced array between values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# create array of values in logspace
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [9]:
# create array of random values
np.random.random((3, 3))

array([[0.90175859, 0.96793591, 0.6928218 ],
       [0.624032  , 0.61701988, 0.19289924],
       [0.12555555, 0.23598873, 0.78190931]])

In [10]:
# create array of random ints
np.random.randint(0, 100, [3, 5])

array([[ 0, 14, 71, 82,  4],
       [46, 38,  3, 55, 31],
       [50, 57, 11, 51, 56]])

In [11]:
# return array of indicies to order input array (ascending)
np.argsort(np.array([5, 18, 3, 6, 14]))

array([2, 0, 3, 4, 1])

In [12]:
x = np.array([5, 18, 3, 6, 14])
x[np.argsort(x)]

array([ 3,  5,  6, 14, 18])

In [13]:
# return array of indicies to order input array (descending)
x.argsort()[::-1]

array([1, 4, 3, 0, 2])

## Shape

In [14]:
X = np.array(np.random.randint(0, 100, (3, 5)))
X

array([[38, 55, 52, 93, 88],
       [94, 71, 45, 34, 37],
       [39, 65, 49, 88, 71]])

In [15]:
np.transpose(X)

array([[38, 94, 39],
       [55, 71, 65],
       [52, 45, 49],
       [93, 34, 88],
       [88, 37, 71]])

In [16]:
# create 1D array
X.flatten()

array([38, 55, 52, 93, 88, 94, 71, 45, 34, 37, 39, 65, 49, 88, 71])

In [17]:
# reshape array
np.reshape(X, (5, 3))

array([[38, 55, 52],
       [93, 88, 94],
       [71, 45, 34],
       [37, 39, 65],
       [49, 88, 71]])

In [18]:
Y = np.random.randint(0, 10, [3, 1])
Y

array([[6],
       [7],
       [6]])

In [19]:
# combine arrays horizontally (by column)
np.hstack((X, Y))

array([[38, 55, 52, 93, 88,  6],
       [94, 71, 45, 34, 37,  7],
       [39, 65, 49, 88, 71,  6]])

In [20]:
Z = np.random.randint(0, 10, [1, 5])
Z

array([[6, 3, 1, 7, 6]])

In [21]:
# combine arrays vertically (by row)
np.vstack((X, Z))

array([[38, 55, 52, 93, 88],
       [94, 71, 45, 34, 37],
       [39, 65, 49, 88, 71],
       [ 6,  3,  1,  7,  6]])

# Vectorization <a name="vect"></a>

In [22]:
# define function to apply to array
def dis_func(a, b):
    # Return a-b if a>b, otherwise return a+b
    if a > b:
        return a - b
    else:
        return a + b

In [23]:
np.vectorize(dis_func)

In [24]:
# pass array and single value to vectorized function
np.vectorize(dis_func)([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

# Linear Algebra <a name="lin_al"></a>

## Matrix definitions

In [25]:
np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
# create matrix of zeros
np.mat(np.zeros((5, 5)))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [27]:
# create matrix of ones
np.mat(np.ones((5, 5)))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [28]:
# create identity matrix
np.mat(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Matrix manipulation

In [29]:
A = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
# matrix spacial dimension
A.ndim

2

In [31]:
# length of matrix
len(A)

3

In [32]:
# matrix shape dimensions
A.shape

(3, 3)

In [33]:
# matrix number of digits
A.size

9

In [34]:
# select selement in third row, second column
A[2, 1]

8

In [35]:
B = np.mat([[6], [2], [-1]])
B

matrix([[ 6],
        [ 2],
        [-1]])

In [36]:
B.shape

(3, 1)

In [37]:
C = A * B
C

matrix([[ 7],
        [28],
        [49]])

In [38]:
C.shape

(3, 1)

## Matrix mulitplication with arrays

In [39]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
# create row vector
B = np.array([[6, 2, -1]])
B

array([[ 6,  2, -1]])

In [41]:
# transpose array into column vector
B.T

array([[ 6],
       [ 2],
       [-1]])

In [42]:
# matrix multiplication
A @ B.T

array([[ 7],
       [28],
       [49]])

In [43]:
np.dot(A, B.T)

array([[ 7],
       [28],
       [49]])